### ISSUE TITLE
Add additional output maps for testing and analysis

### ISSUE THREAD

**Issue by akretchun** [LANDIS-II-Foundation/Extension-NECN-Hydro-Succession#1]
Add output maps for sum(LAI), shade class, and soil moisture.

**Comment by akretchun** [comment]
This was implemented and then erased in a commit/merge revert. Need to redo it

**Comment by akretchun** [comment]
@rmscheller What makes the most sense to map soil moisture through time, field cap/wilting point?

**Comment by rmscheller** [comment]
Available water.

**Comment by rmscheller** [comment]
Or AET/PET?

**Comment by akretchun** [comment]
AET/PET makes some sense to me, maybe as a complement to the water budget maps

**Comment by akretchun** [comment]
Added soil moisture maps, ready for testing. Will do shade class next

**Comment by akretchun** [comment]
So thinking on this a little more I added a map of available water (SiteVar) to go along with the Annual Water Budget Maps. I think this gives us a few maps that reflect soil conditions pertinent for plant growth
