### ISSUE TITLE
Update assembly info to make successful installer

### ISSUE THREAD

**Issue by akretchun** [LANDIS-II-Foundation/Extension-NECN-Hydro-Succession#12]
Need to update 'deploy' folder and assembly info so the naming convention ('NECN-H') is consistent

**Comment by mslucash** [comment]
I tried to use the new installer on the repo but it did not work and generated this error message.
[Landis-log.txt](https://github.com/LANDIS-II-Foundation/Extension-NECN-Hydro-Succession/files/984115/Landis-log.txt)

**Comment by rmscheller** [comment]
Alec, I can't figure out where this _Hydro is hiding.  I changed all naming conventions to Landis.Extension.Succession.NECN (which now isn't distinct from the standard version) and yet there it is again.   Any ideas?

**Comment by akretchun** [comment]
And its not possible that it could be hiding in anything that isn't being  overwritten by the new installer?

**Comment by rmscheller** [comment]
No.  Only the extension should know its name, so to speak.

**Comment by rmscheller** [comment]
Melissa, are you using the v0.5 installer?  4.2 is out of date.
