### ISSUE TITLE
Available Water less than zero

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Extension-NECN-Hydro-Succession#13]
Right now if FC minus WP is less than zero, NECN-Hydro triggers an error and stops running.
  
Perhaps we need to set available water to zero if it's negative?

**Comment by rmscheller** [comment]
FC and WP are fixed inputs, correct?  As such, we should never allow FC < WP, as that is physically impossible.  Or am I mis-understanding the question?

**Comment by akretchun** [comment]
Sometimes individual cells or small groups of cells can overlap in ways that produce negative available water. This happens sometimes when turning SSURGO polygons into raster or when there are errors in the SSURGO database. I'm going to have NECN_H just move negative values up to 0 and produce a warning message

**Comment by akretchun** [comment]
Should this be set using waterContent or soil water hold capacity (swhc)?

**Comment by rmscheller** [comment]
Available water should never go negative.  Nor should swhc.  Both should throw an error message and quit - and provide cell location for map debugging?

**Comment by akretchun** [comment]
We are requiring users to fix whatever problems may exist in the input data themselves and doing no corrections to swhc within NECN_Hydro
