### ISSUE TITLE
Zeros in NECN_Hydro-succession-log.csv

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Extension-NECN-Hydro-Succession#16]
There are a LOT of zeros  in the succession-log.csv output file.  AG_NPPC, litterfall, C_Leaf, all soil C pools just to name a few.

**Comment by mslucash** [comment]
The most important output parameters to report (so I can troubleshoot the mineral N issue) are:
1) TotalNdeposition
2) StreamN
3) N uptake
4) Nvol
5) GrossMineralization
6) Nresorbed

**Comment by mslucash** [comment]
I think it makes sense to investigate these zeros first:
In time=0, litterfall, C_Leaf, C_FRoot, C_CRoot and C_Wood, N_Leaf, N_FRoot, N_Wood, N_CRoot are all zero, even though they are pools.

**Comment by akretchun** [comment]
The zeroes only appear at year 0. It doesn't appear to be a reporting issue (these values appear to actually be 0), but I don't have any more time to look into it today. I'll pick it up again at the end of the week

**Comment by rmscheller** [comment]
Tweak to PlugIn.cs should resolve most of the zeros issue.  Many cannot be removed at year 0 as the model has not yet run at that time.
