### ISSUE TITLE
Mineral N triggering error

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Extension-NECN-Hydro-Succession#17]
When I try to run my VIFF landscape, I get the error message below.  When I run my landscape in calibrate mode, I can see that it's a problem with MANY species not getting any N.  The trees have available water but limitN=0.

2017-06-02 14:19:22,165 -   N ALLOCATION CALCULATION = NaN!  
2017-06-02 14:19:22,165 -   Nallocation=0.00, NAllocTotal=0.00, relativeNallocation=NaN.
2017-06-02 14:19:22,165 -   Wood=0.00, Leaf=0.00.

**Comment by mslucash** [comment]
Based on my conversation with Alec, I tried to bump up my N tto get it to run (it worked for him at a single-cell). I increased Ndep by an order of magnitude and increased mineralN up to 55, and I still had the error right away.  
Anyway... let me know if you want me to dig into the N budget and see what is causing the problem.

**Comment by rmscheller** [comment]
Melissa, yes, please investigate further.  
In the monthly log file:  Is N being deposited?
Are the soil N values (from map) being correctly read?  It is odd that soil N is zero at time zero as there is no spin-up.

**Comment by mslucash** [comment]
Mineral N is being read in correctly and Ndep is occurring.  

I traced the problem back to 
AvailableN.cs line 126
This function:
double Nallocation = 1- Math.Exp((-Roots.CalculateCoarseRoot(cohort, cohort.WoodBiomass)*0.02));
returns a zero because the coarse root biomass is zero.
Then Nallocation is iterated in NAllocTotal (line 134) and then the denominator in L177, which causes the NA.
That root biomass is zero is not surprising because it's also zero in the csv file, along with many other parameters.  See attached file.
![zerosmeloutput](https://cloud.githubusercontent.com/assets/7819936/26804129/bf358a84-49fb-11e7-9473-93335bf65d8e.JPG)

**Comment by rmscheller** [comment]
It's funny this never came up in my prior testing.  At any rate, it seems
we need to initialize course roots.  I'll code that up tomorrow.  Anything
else needs initializing?

--
Rob Scheller
rmscheller@gmail.com

**Comment by mslucash** [comment]
Yes, maps of DeadSurface, i.e. CWD+Snags.

Melissa

**Comment by rmscheller** [comment]
Dead Surface Wood is initialized:  PlugIn.cs line 122.

**Comment by rmscheller** [comment]
I changed up the year 0 reporting so that it should include more of the data - but not everything will be possible for year 0.  Can you re-test?

**Comment by akretchun** [comment]
I can take a look at it later on this afternoon if needed

**Comment by mslucash** [comment]
Like we discussed,  it would be good if the input maps were checked for zeros within the active cells.  If zeros are found in active cells, I think the model should stop, tell the user which map had the error and which row/ column it encountered the.error.  I also made a R script yesterday that makes it easy to spot errors in the input maps.

**Comment by rmscheller** [comment]
Has this issue been resolved?

**Comment by mslucash** [comment]
Yes fixed.
