### ISSUE TITLE
Coarse root biomass maps

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Extension-NECN-Hydro-Succession#18]
Are you sure it makes sense to include coarse root biomass as an input?  By feeding in a map of coarse root biomass directly from FIA, you are potentially de-coupling AGB and BGB (i.e. having spots where maps have lots of coarse root biomass but there is little aboveground biomass, because of the variation in imputation),   Maybe you want to run the model to make a map of total biomass at time=0 and THEN use fixed ratios to calculate coarse root biomass and THEN run the model.  Or have BGB calculated on the fly as a proportion of AGB as we've done in the past.  I guess I support the use of the map, I just wanted to describe the problem that might result from using FIA's publically available maps of coarse root biomass.

**Comment by rmscheller** [comment]
No, I like it as is.  Post-harvesting will be much dead roots and no AGB or DWD.

**Comment by mslucash** [comment]
Oh right. Makes sense now.

On Jun 6, 2017 7:39 AM, "Robert Scheller" <notifications@github.com> wrote:

No, I like it as is. Post-harvesting will be much dead roots and no AGB or
DWD.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/LANDIS-II-Foundation/Extension-NECN-Hydro-Succession/issues/18#issuecomment-306507051>,
or mute the thread
