### ISSUE TITLE
Century-succession-log NaN output error

### ISSUE THREAD

**Issue by akretchun** [LANDIS-II-Foundation/Extension-NECN-Hydro-Succession#2]
Century-succession-log.csv produces NaNs. Intended design is output row for every unique ClimateRegion x SoilWaterHoldingCapacity combination. Soil water holding capacity values are binned by integers.

**Comment by akretchun** [comment]
I think we should get rid of the SWHC in the primary log file and just sort by climate region. If users want to do more in-depth spatial analysis, they can use the maps

**Comment by rmscheller** [comment]
That seems reasonable.

**Comment by akretchun** [comment]
Eliminated SWHC so now it just reports outputs by ClimateRegion. I think we also need to note in the UG that users should get in the habit of naming climate regions 'climate1, climate2, etc' in place of 'eco1, eco2, etc' so there's no confusion when the log file reports out the climate region in that column
