### ISSUE TITLE
Mysterious new climate error

### ISSUE THREAD

**Issue by akretchun** [LANDIS-II-Foundation/Extension-NECN-Hydro-Succession#23]
@rmscheller Is this the error you were getting before?
[Landis-log.txt](https://github.com/LANDIS-II-Foundation/Extension-NECN-Hydro-Succession/files/1356915/Landis-log.txt)

I am trying to run Lake Tahoe and suddenly this new error has appeared. I tried multiple climate files and same thing every time

**Comment by akretchun** [comment]
But it works when I run the same inputs directly out of the SCRAPPELE Gir repo. I don't get this

**Comment by rmscheller** [comment]
When did you last run the installer?

**Comment by rmscheller** [comment]
p.s. No, this is not at all the error I was getting.

**Comment by rmscheller** [comment]
I don't understand - it works when and not when?

**Comment by akretchun** [comment]
Re-installed Hydro and it fixed the issue. Must have been because I installed a new SCRAPPLE
