### ISSUE TITLE
prob-establish-log.csv not working properly

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Extension-NECN-Hydro-Succession#24]
The pest file does not report the values for the final column for AvgProbEst.  They are empty cells.

Also, the pest file looks fine (except issue above) for a single cell sim.  But for an entire landscape, the pest file has more than one entry for each spp*climate region.  See attached jpg  There should be one entry for AmBeech in CLIM01, but there are 38 before it swiches to CLIM02.
![pest_file_error](https://user-images.githubusercontent.com/7819936/31617873-3c2af978-b245-11e7-8845-cf2135f38a1d.JPG)

**Comment by rmscheller** [comment]
Fixed, not tested.  New installer (v0.7) available.

**Comment by mslucash** [comment]
You fixed the second problem (hurray!), but not the first one.  This one.
The pest file does not report the values for the final column for AvgProbEst. They are empty cells.

**Comment by rmscheller** [comment]
Extra column removed.  New installer.

**Comment by mslucash** [comment]
I'm confused; I don't understand why you removed a column.  We are missing at least one column of values.  In previous versions of NECN, we had a column marked "OtherAdj" and "ProbEst", which are technically both missing from the output file.  The p-est output file should look like this:


Time |Species| ClimateRegion | SWHC |AvgTempMult | AvgMinJanTempMult | AvgSoilMoistureMult | OtherAdjustMult | AvgProbEst

**Comment by rmscheller** [comment]
SWHC is no longer a column.
