### ISSUE TITLE
Annual water budget maps incorrect

### ISSUE THREAD

**Issue by akretchun** [LANDIS-II-Foundation/Extension-NECN-Hydro-Succession#26]
The 'Annual Water Budget' maps, defined as ppt-AET, are not producing realistic values. In Lake Tahoe runs they produce integers of very low values (e.g. 1), where in reality the numbers are in the high hundreds (e.g. 800mm). I'm not sure where the error in calculation occurs, but monthly AET should be summed to create AnnualAET, which is then subtracted from annual precip. Alternatively, I guess it could calculate monthly ppt-monthly AET and then sum them for a given year

**Comment by akretchun** [comment]
@mslucash I included an individual year's monthly climate data from Tahoe (1980LTB.csv) in the Test_SpatialIgnitions folder in your main scheller_lab directory. I also replaced the climate generator text file. They should be functional to use for monthly testing of these maps

**Comment by rmscheller** [comment]
Alec, has this been resolved?

**Comment by akretchun** [comment]
Not yet, still looking into it

**Comment by mslucash** [comment]
I said I'd look through the SoilWater code this week, but I just got waylaid with the single cell problem.

**Comment by akretchun** [comment]
These look much better! They're in the right order of magnitude now, so I am going to consider this issue closed, unless further testing warrants its re-opening. Thank you!
