### ISSUE TITLE
p-est values >1

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Extension-NECN-Hydro-Succession#28]
In the prob-establish-log.csv file, we have AvgProbEst values that exceed 1.

**Comment by mslucash** [comment]
Actually all the output (columns D-G) looks funky.  All the multipliers look off- Avg Temp >1, AvgMinJan and AvgSoil go up to 22.  Even if you just have one climate region.

**Comment by rmscheller** [comment]
The average calculation was not resetting to zero.  Fixed, new installer, committed.
