### ISSUE TITLE
Annual water budget output maps are reporting SOMTC

### ISSUE THREAD

**Issue by akretchun** [LANDIS-II-Foundation/Extension-NECN-Hydro-Succession#3]
'Annual water budget' maps are reporting SOMTC, as defined in Output.cs. It supposed to be ppt-AET.

**Comment by akretchun** [comment]
I added the functionality to calculate Annual Water Budget as ppt - aet but it needs testing

**Comment by akretchun** [comment]
@rmscheller if you get a few minutes in the next few days, would you mind taking a look at these? They still aren't properly outputting and I am not exactly sure why. Thanks!

**Comment by rmscheller** [comment]
I fixed a couple things, committed and pushed.

**Comment by akretchun** [comment]
Excellent, thanks! I'll test today

**Comment by akretchun** [comment]
commenting to remind you to try and commit/push and see if your previous changes were reverted out of the master

**Comment by rmscheller** [comment]
Updated.

**Comment by akretchun** [comment]
Revisiting this issue now that Paul Henne has provided historic basin-wide averages of ppt-aet. His values range from ~600-1200mm, whereas our outputs at the moment range from 0-5, so something is screwy. Will dig into code and try to suss out whats going on

**Comment by rmscheller** [comment]
Note that I adjusted the maps to be integers.  Multiply outputs by 1000?

**Comment by akretchun** [comment]
Hhhmm good point, I'll have to play around with the math on that. 1000 might be too high of a correction factor. Our historic precip values are annual totals (about 1000mm/yr) and AET is mean for the year (about 150-200mm), so this might not be lining up exactly with how NECN-H is keeping track of these values

**Comment by akretchun** [comment]
This is a duplicate of the Annual water budget maps issue that was just closed. Similarly, values are in the right range now, so this is resolved unless further testing requires its re-opening
