### ISSUE TITLE
Custom outputs for Tahoe project

### ISSUE THREAD

**Issue by akretchun** [LANDIS-II-Foundation/Extension-NECN-Hydro-Succession#30]
For our Lake Tahoe project, the smoke emissions modelers want a few custom output maps to use as inputs for their work. Namely:

    Canopy leaf biomass
    Dead wood biomass
    Surface litter and duff

**Comment by rmscheller** [comment]
Completed and tested.  See: Scrapple\testing\Test_NECN_H.  Installer 0.9.3

**Comment by akretchun** [comment]
Rob, where are these outputs supposed to be writing?

**Comment by rmscheller** [comment]
They should be in the NECN sub-folder.
