### ISSUE TITLE
error in InitialDeadWoodSurfaceMapName and InitialDeadCoarseRootsMapName

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Extension-NECN-Hydro-Succession#31]
The values in the input file do not match the output in the NECN_Hydro-succession-log.csv at time=0.  
Map of DeadWoodBiomass-1.img is very close to input (InitialDeadWoodSurfaceMapName) so for that parm, it seems like an error only in the csv file.
We don't make maps of dead coarse roots so I'm not sure about that one.

**Comment by rmscheller** [comment]
So this is only a year 0 problem?  Should we deactivate year 0 now that we no longer have spinup?

**Comment by mslucash** [comment]
False alarm.  The maps are in biomass, the output in the maps and csv file is in Carbon.  Oh and I checked all the parms to make sure they matched between the inputs and time=0 in the main succession log file and checked all the values in the short file to make sure they are correct.  They all look fine.
