### ISSUE TITLE
Year 0 fine fuel biomass

### ISSUE THREAD

**Issue by akretchun** [LANDIS-II-Foundation/Extension-NECN-Hydro-Succession#32]
Add dead structural leaf material as a function of dead wood map

**Comment by rmscheller** [comment]
Added new functionality and created new installer 0.9.4.
See: https://github.com/LANDIS-II-Foundation/Extension-NECN-Hydro-Succession/commit/f546312a859d3c2301cd4817647f9ca5ba815ef7
