### ISSUE TITLE
Add Dead Wood C tracking functionality

### ISSUE THREAD

**Issue by akretchun** [LANDIS-II-Foundation/Extension-NECN-Hydro-Succession#34]
Specific for the Lake Tahoe West project, it would be great to have an idea of how much biomass was transferred into the dead wood pool from specific cohorts, or alternatively, some sort of 'big wood', 'small wood' cutoff.

**Comment by rmscheller** [comment]
Alec,  Let's move this to Scrapple, where I'll add 'SpecialDeadWood' table.

--
Rob Scheller
rmscheller@gmail.com

**Comment by rmscheller** [comment]
Alec, Let's move this to SCRAPPLE where I'll add a SpecialDeadWood table.
