### ISSUE TITLE
SoilWaterHoldingCapacity in csv file is zero

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Extension-NECN-Hydro-Succession#39]
Trees are growing just fine and AvailableWater maps have values so it's likely just a reporting error.

![image](https://user-images.githubusercontent.com/7819936/38896497-b972f362-4247-11e8-8493-ea42272a2f26.png)

**Comment by rmscheller** [comment]
Which log file is this?

**Comment by rmscheller** [comment]
I see, the primary log file.  Should this column be removed?  There is not a single SWHC per climate region.  We could report average but is that meaningful across large climate regions?

**Comment by rmscheller** [comment]
My concern is that an average will be very broad and may mis-direct naive users; particularly those familiar with the prior definitions of ecoregion.

**Comment by rmscheller** [comment]
Therefore I prefer to omit.

**Comment by mslucash** [comment]
That's fine. Did you fix the log file already?

**Comment by rmscheller** [comment]
Yes, will show up in next release.
