### ISSUE TITLE
Change labels for functional group H20 and T limits

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Extension-NECN-Hydro-Succession#5]
It needs to be more clear that the functional group H20 and T limits apply to growth only, not establishment.

**Comment by akretchun** [comment]
Where is the best place to clarify this? Documentation or calibrate log file?

**Comment by rmscheller** [comment]
In the User Guide.  I don't know that the code needs to change - although doing so would be useful for us coders, too!

**Comment by rmscheller** [comment]
Also the calibrate log file?  I don't remember off-hand what all is listed.

**Comment by akretchun** [comment]
Nah, I don't think its appropriate to note there, its just where the limits are most frequently accessed by users. I'll just put it in the Users Guide

**Comment by akretchun** [comment]
I suggest a name change to these parameters. I know that we retained the PPDF etc names because they correspond to Century, but it seems we are far from that now. How about 'TempCurve' and 'MoistureCurve'? And then we can note in the Users Guide the old names

**Comment by rmscheller** [comment]
Yes, a good idea.  Consistency between UG and code will make everyone's life easier.

**Comment by akretchun** [comment]
I pushed a commit with these changes but couldn't rebuild as there is increased security on InputParametersParser.cs. How do I get access to update the ppdf names?

**Comment by akretchun** [comment]
Updated in the UG and w/in the code
