### ISSUE TITLE
Increase allowable Field Capacity input

### ISSUE THREAD

**Issue by akretchun** [LANDIS-II-Foundation/Extension-NECN-Hydro-Succession#7]
Increase it to 1.0

**Comment by rmscheller** [comment]
Why 1.0?  That wold be extreme!  But maybe not unreasonable for wetland soils?

**Comment by akretchun** [comment]
Agreed it would be really extreme. Maybe not all the way to 1.0, but its at 0.5 right now and I thought that would definitely be too low a cutoff even in wetter Mid Western soils

**Comment by rmscheller** [comment]
Agreed.

**Comment by akretchun** [comment]
Changed it to 0.75
