### ISSUE TITLE
NECN-H output folder no longer being written

### ISSUE THREAD

**Issue by akretchun** [LANDIS-II-Foundation/Extension-NECN-Hydro-Succession#9]
Folder that contains output maps is not being written anymore. Likely something screwed up when we replaced 'Century' with 'NECN_H' in output names

**Comment by akretchun** [comment]
This is fixed witin InputParameterParser.cs by changing 'readoptionalvar' to 'readvar'

**Comment by akretchun** [comment]
These need to be produced automatically. I'm not sure how to remove the naming requirement outlined in the Input Parameter Parser

**Comment by rmscheller** [comment]
We could just remove those parameters altogether and provide the names, e.g., Outputs.cs. line 518.

**Comment by akretchun** [comment]
Yeah, I think removing them as user-name provided inputs within the code is best, since they are no longer included in the input file. I'll take a look at that line and see if I can get it done. Thanks!

**Comment by akretchun** [comment]
Now produces 'NECN_Hydro' folder that contains all the output maps we are currently writing.
